USE dogalert;

ALTER TABLE Reportes
    MODIFY COLUMN Fecha_Conservacion_Hasta DATE NULL DEFAULT NULL;

SELECT COLUMN_NAME, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_TYPE
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'Reportes'
  AND COLUMN_NAME = 'Fecha_Conservacion_Hasta';