USE dogalert;

CREATE TABLE IF NOT EXISTS Usuarios (
    ID_Usuario INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(150) NOT NULL,
    Telefono VARCHAR(20),
    Correo VARCHAR(50) NOT NULL UNIQUE,
    Contrasena VARCHAR(255) NOT NULL,
    Rol ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER',
    Mayor_Edad TINYINT(1) DEFAULT 1,
    Aviso_Privacidad_Aceptado TINYINT(1) NOT NULL, 
    Consentimiento_Contacto TINYINT(1) DEFAULT 0,
    Estado_Cuenta ENUM('ACTIVA', 'INACTIVA', 'SUSPENDIDA') DEFAULT 'ACTIVA',
    Fecha_Creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Fecha_Ultimo_Acceso TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);